package ca.blackperl.toursdb;
// Generated Mar 27, 2016 10:34:39 PM by Hibernate Tools 4.3.1.Final

/**
 * Countries generated by hbm2java
 */
public class Countries implements java.io.Serializable {

	private String countryIsoCode;
	private String country;
	private String region;

	public Countries() {
	}

	public Countries(String countryIsoCode, String country) {
		this.countryIsoCode = countryIsoCode;
		this.country = country;
	}

	public Countries(String countryIsoCode, String country, String region) {
		this.countryIsoCode = countryIsoCode;
		this.country = country;
		this.region = region;
	}

	public String getCountryIsoCode() {
		return this.countryIsoCode;
	}

	public void setCountryIsoCode(String countryIsoCode) {
		this.countryIsoCode = countryIsoCode;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

}
