package ca.blackperl.toursdb;
// Generated Mar 27, 2016 10:34:39 PM by Hibernate Tools 4.3.1.Final

/**
 * FlightsHistory generated by hbm2java
 */
public class FlightsHistory implements java.io.Serializable {

	private FlightsHistoryId id;

	public FlightsHistory() {
	}

	public FlightsHistory(FlightsHistoryId id) {
		this.id = id;
	}

	public FlightsHistoryId getId() {
		return this.id;
	}

	public void setId(FlightsHistoryId id) {
		this.id = id;
	}

}
