package ca.blackperl.toursdb;
// Generated Mar 27, 2016 10:34:39 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * FlightsHistoryId generated by hbm2java
 */
public class FlightsHistoryId implements java.io.Serializable {

	private String flightId;
	private Integer segmentNumber;
	private String origAirport;
	private Date departTime;
	private String destAirport;
	private Date arriveTime;
	private Character meal;
	private Double flyingTime;
	private Integer miles;
	private String aircraft;
	private String status;

	public FlightsHistoryId() {
	}

	public FlightsHistoryId(String flightId, Integer segmentNumber, String origAirport, Date departTime,
			String destAirport, Date arriveTime, Character meal, Double flyingTime, Integer miles, String aircraft,
			String status) {
		this.flightId = flightId;
		this.segmentNumber = segmentNumber;
		this.origAirport = origAirport;
		this.departTime = departTime;
		this.destAirport = destAirport;
		this.arriveTime = arriveTime;
		this.meal = meal;
		this.flyingTime = flyingTime;
		this.miles = miles;
		this.aircraft = aircraft;
		this.status = status;
	}

	public String getFlightId() {
		return this.flightId;
	}

	public void setFlightId(String flightId) {
		this.flightId = flightId;
	}

	public Integer getSegmentNumber() {
		return this.segmentNumber;
	}

	public void setSegmentNumber(Integer segmentNumber) {
		this.segmentNumber = segmentNumber;
	}

	public String getOrigAirport() {
		return this.origAirport;
	}

	public void setOrigAirport(String origAirport) {
		this.origAirport = origAirport;
	}

	public Date getDepartTime() {
		return this.departTime;
	}

	public void setDepartTime(Date departTime) {
		this.departTime = departTime;
	}

	public String getDestAirport() {
		return this.destAirport;
	}

	public void setDestAirport(String destAirport) {
		this.destAirport = destAirport;
	}

	public Date getArriveTime() {
		return this.arriveTime;
	}

	public void setArriveTime(Date arriveTime) {
		this.arriveTime = arriveTime;
	}

	public Character getMeal() {
		return this.meal;
	}

	public void setMeal(Character meal) {
		this.meal = meal;
	}

	public Double getFlyingTime() {
		return this.flyingTime;
	}

	public void setFlyingTime(Double flyingTime) {
		this.flyingTime = flyingTime;
	}

	public Integer getMiles() {
		return this.miles;
	}

	public void setMiles(Integer miles) {
		this.miles = miles;
	}

	public String getAircraft() {
		return this.aircraft;
	}

	public void setAircraft(String aircraft) {
		this.aircraft = aircraft;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlightsHistoryId))
			return false;
		FlightsHistoryId castOther = (FlightsHistoryId) other;

		return ((this.getFlightId() == castOther.getFlightId()) || (this.getFlightId() != null
				&& castOther.getFlightId() != null && this.getFlightId().equals(castOther.getFlightId())))
				&& ((this.getSegmentNumber() == castOther.getSegmentNumber())
						|| (this.getSegmentNumber() != null && castOther.getSegmentNumber() != null
								&& this.getSegmentNumber().equals(castOther.getSegmentNumber())))
				&& ((this.getOrigAirport().equals(castOther.getOrigAirport()))
						|| (this.getOrigAirport() != null && castOther.getOrigAirport() != null
								&& this.getOrigAirport().equals(castOther.getOrigAirport())))
				&& ((this.getDepartTime() == castOther.getDepartTime()) || (this.getDepartTime() != null
						&& castOther.getDepartTime() != null && this.getDepartTime().equals(castOther.getDepartTime())))
				&& ((this.getDestAirport().equals(castOther.getDestAirport()))
						|| (this.getDestAirport() != null && castOther.getDestAirport() != null
								&& this.getDestAirport().equals(castOther.getDestAirport())))
				&& ((this.getArriveTime() == castOther.getArriveTime()) || (this.getArriveTime() != null
						&& castOther.getArriveTime() != null && this.getArriveTime().equals(castOther.getArriveTime())))
				&& ((this.getMeal() == castOther.getMeal()) || (this.getMeal() != null && castOther.getMeal() != null
						&& this.getMeal().equals(castOther.getMeal())))
				&& ((this.getFlyingTime() == castOther.getFlyingTime()) || (this.getFlyingTime() != null
						&& castOther.getFlyingTime() != null && this.getFlyingTime().equals(castOther.getFlyingTime())))
				&& ((this.getMiles().equals(castOther.getMiles())) || (this.getMiles() != null
						&& castOther.getMiles() != null && this.getMiles().equals(castOther.getMiles())))
				&& ((this.getAircraft().equals(castOther.getAircraft())) || (this.getAircraft() != null
						&& castOther.getAircraft() != null && this.getAircraft().equals(castOther.getAircraft())))
				&& ((this.getStatus().equals(castOther.getStatus())) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFlightId() == null ? 0 : this.getFlightId().hashCode());
		result = 37 * result + (getSegmentNumber() == null ? 0 : this.getSegmentNumber().hashCode());
		result = 37 * result + (getOrigAirport() == null ? 0 : this.getOrigAirport().hashCode());
		result = 37 * result + (getDepartTime() == null ? 0 : this.getDepartTime().hashCode());
		result = 37 * result + (getDestAirport() == null ? 0 : this.getDestAirport().hashCode());
		result = 37 * result + (getArriveTime() == null ? 0 : this.getArriveTime().hashCode());
		result = 37 * result + (getMeal() == null ? 0 : this.getMeal().hashCode());
		result = 37 * result + (getFlyingTime() == null ? 0 : this.getFlyingTime().hashCode());
		result = 37 * result + (getMiles() == null ? 0 : this.getMiles().hashCode());
		result = 37 * result + (getAircraft() == null ? 0 : this.getAircraft().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
