package ca.blackperl.toursdb;
// Generated Mar 27, 2016 10:34:39 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * FlightavailabilityId generated by hbm2java
 */
public class FlightavailabilityId implements java.io.Serializable {

	private String flightId;
	private int segmentNumber;
	private Date flightDate;

	public FlightavailabilityId() {
	}

	public FlightavailabilityId(String flightId, int segmentNumber, Date flightDate) {
		this.flightId = flightId;
		this.segmentNumber = segmentNumber;
		this.flightDate = flightDate;
	}

	public String getFlightId() {
		return this.flightId;
	}

	public void setFlightId(String flightId) {
		this.flightId = flightId;
	}

	public int getSegmentNumber() {
		return this.segmentNumber;
	}

	public void setSegmentNumber(int segmentNumber) {
		this.segmentNumber = segmentNumber;
	}

	public Date getFlightDate() {
		return this.flightDate;
	}

	public void setFlightDate(Date flightDate) {
		this.flightDate = flightDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlightavailabilityId))
			return false;
		FlightavailabilityId castOther = (FlightavailabilityId) other;

		return ((this.getFlightId() == castOther.getFlightId()) || (this.getFlightId() != null
				&& castOther.getFlightId() != null && this.getFlightId().equals(castOther.getFlightId())))
				&& (this.getSegmentNumber() == castOther.getSegmentNumber())
				&& ((this.getFlightDate() == castOther.getFlightDate())
						|| (this.getFlightDate() != null && castOther.getFlightDate() != null
								&& this.getFlightDate().equals(castOther.getFlightDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFlightId() == null ? 0 : this.getFlightId().hashCode());
		result = 37 * result + this.getSegmentNumber();
		result = 37 * result + (getFlightDate() == null ? 0 : this.getFlightDate().hashCode());
		return result;
	}

}
